### ISSUE TITLE
bevy_easings fails to compile with rust 1.55

### ISSUE THREAD

**Issue by rparrett** [mockersf/bevy_extra#12]
This is possibly related to #11, although that predates rust 1.55 and doesn't seem like an actual solution. But perhaps that user was using rust beta?

```
error[E0658]: use of unstable library feature 'float_interpolation'
   --> bevy_easings/src/implemented.rs:125:49
    |
125 |                 EaseValue(Val::Percent(self_val.lerp(&other_val, scalar)))
    |                                                 ^^^^
    |
    = note: see issue #86269 <https://github.com/rust-lang/rust/issues/86269> for more information

error[E0308]: mismatched types
   --> bevy_easings/src/implemented.rs:125:54
    |
125 |                 EaseValue(Val::Percent(self_val.lerp(&other_val, scalar)))
    |                                                      ^^^^^^^^^^
    |                                                      |
    |                                                      expected `f32`, found `&f32`
    |                                                      help: consider removing the borrow: `other_val`
```

I am able to reproduce this consistently by

```sh
rustup update stable
rustup install 1.54

git clone git@github.com:mockersf/bevy_extra.git
cd bevy_extra/bevy_easings
git checkout 68d53df
cargo clean && cargo +stable test #fails
cargo clean && cargo +1.54 test   #succeeds
```

This seems a little wacky to me, because I can't find any information about 1.55 related to `float_interpolation`.

**Comment by mockersf** [comment]
It is related to https://github.com/rust-lang/rust/issues/86269:
* on June 17 the pr to add `lerp` to `std::f32` was merged - https://github.com/rust-lang/rust/pull/85925
* since then building with nightly would fail
* since the 1.55 release, rust stable has knowledge of the code behind a feature flag even though you can't enable it on stable as it's unstable - meaning you can't have your own `lerp` on stable and can't use the `std::f32` one.

I'm not sure how to fix this other than renaming `lerp` to... something else until the feature is stabilised and then move over to  `std::f32::lerp`

@Carlton-perkins you seemed to have an idea in https://github.com/mockersf/bevy_extra/pull/11#issuecomment-913168803 but I'm not sure I understand what you mean?

**Comment by Carlton-Perkins** [comment]
> @Carlton-Perkins you seemed to have an idea in [#11 (comment)](https://github.com/mockersf/bevy_extra/pull/11#issuecomment-913168803) but I'm not sure I understand what you mean?

Was completely overthinking the problem when I wrote that. This can just be fixed until the feature is stabilized via trait method disambiguation. And whenever the feature is stabilized, its a simple fix to just swap around the references to values like the original error suggests.

Fix is on PR #13.

**Comment by sphinxc0re** [comment]
Will there be a minor release soon that includes the fix?

**Comment by parasyte** [comment]
#13 is merged. We need a new release.
